server:
  port: 3000

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.auth0.example: TRACE

spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/amped
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    database: MYSQL
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: {CLIENT_ID}
            client-secret: {CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://{DOMAIN}/
